<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
<meta charset="UTF-8">
</head>
<h1 id="section">20250227</h1>
<ul>
<li>Made a check for tax return</li>
<li>30 minutes walk</li>
<li>Journaling</li>
<li>worked hard</li>
</ul>
<h2 id="test-coverage-threshold-with-pytest-cov">test coverage threshold
with <code>pytest-cov</code></h2>
<p>We have a GitHub Actions workflow that runs tests and checks test
coverage. I noticed that a run didn’t fail even though it seemed like it
should have at first glance.</p>
<p>The confusing part is that, it said “FAIL” in the result messages by
<code>pytest-cov</code>, but did not exit with code 1 (Instead, we got
exit code 0), which</p>
<p><strong>When the task fails</strong></p>
<pre><code>Run poetry run pytest --cov=. --cov-fail-under=72
FAIL Required test coverage of 72% not reached. Total coverage: 70.60%

Error: Process completed with exit code 1.</code></pre>
<p><strong>When the task succeeds even though the test coverage is under
the given value</strong></p>
<pre><code>Run poetry run pytest --cov=. --cov-fail-under=71
FAIL Required test coverage of 71% not reached. Total coverage: 70.60%

# exit with code 0. thus, the GitHub Actions workflow does not fail.</code></pre>
<p>I didn’t have much time today to dive deep into the code base
(sorry!), but it looks like the comparition is being made using the
rounded value with the specified precision.</p>
<p><a
href="https://github.com/pytest-dev/pytest-cov/blob/4732d50f2322a6e0ea480a6c400fbc96f78283bb/src/pytest_cov/plugin.py#L380">pytest-cov/src/pytest_cov/plugin.py</a></p>
<pre><code>class CovPlugin:
    def pytest_terminal_summary(self, terminalreporter):
        if self.options.cov_fail_under is not None and self.options.cov_fail_under &gt; 0:
            failed = self.cov_total &lt; self.options.cov_fail_under
            message = &#39;{fail}Required test coverage of {required}% {reached}. &#39; &#39;Total coverage: {actual:.2f}%\n&#39;.format(
                required=self.options.cov_fail_under,
                actual=self.cov_total,
                fail=&#39;FAIL &#39; if failed else &#39;&#39;,
                reached=&#39;not reached&#39; if failed else &#39;reached&#39;,
            )</code></pre>
<p>This condition in <code>pytest-cov</code> reports FAIL by comparing
(unrounded?) coverage total and the given value for
<code>--cov-fail-under</code>. However,</p>
<p><a
href="https://github.com/nedbat/coveragepy/blob/1aecfa7ae2a81aa9c278cbb43718ae7e4bdcf5b5/coverage/results.py#L399">coveragepy/coverage/results.py</a></p>
<pre><code>def should_fail_under(total: float, fail_under: float, precision: int) -&gt; bool:
    &quot;&quot;&quot;Determine if a total should fail due to fail-under.

    `total` is a float, the coverage measurement total. `fail_under` is the
    fail_under setting to compare with. `precision` is the number of digits
    to consider after the decimal point.

    Returns True if the total should fail.

    &quot;&quot;&quot;
    # We can never achieve higher than 100% coverage, or less than zero.
    if not (0 &lt;= fail_under &lt;= 100.0):
        msg = f&quot;fail_under={fail_under} is invalid. Must be between 0 and 100.&quot;
        raise ConfigError(msg)

    # Special case for fail_under=100, it must really be 100.
    if fail_under == 100.0 and total != 100.0:
        return True

    return round(total, precision) &lt; fail_under</code></pre>
<p>The condition rounds the total test coverage, leading to the
mismatch.</p>
<p>This might be related to this <a
href="https://github.com/pytest-dev/pytest-cov/issues/638">issue
#638</a></p>
<p>Anyway, I’m glad I could find out what happened.</p>
<hr />
<p>TODO:</p>
<ul>
<li>Upgrade Mastodon used for my server</li>
<li>Review tax documents</li>
<li>File the tax return</li>
<li>Update DL with my new name (20250305)</li>
<li>Create a Go script to send a request to OpenAI API</li>
<li>2044E, F</li>
<li>live plants for my desk, probably Pothos</li>
</ul>
<hr />
<p><a href="../../index.html">index</a> <a
href="20250226.html">20250226</a> <a
href="20250228.html">20250228</a></p>
